### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [TsNikolay/Tetris#1]
1. It's better to use collections instead of switch/case statement, for example here: https://github.com/TsNikolay/Tetris/blob/1fd7dfc836043c7e0c28b1a5a1bb184102201c16/js/controller.js#L67-L96
2. We do not need class syntax for configuration, you can export just object
3. Following can be refactored like here: https://github.com/TsNikolay/Tetris/blob/1fd7dfc836043c7e0c28b1a5a1bb184102201c16/js/game.js#L102-L107
to:
```js
    for (let y = 0; y < this.playfield.lengtht; y++) {
      playfield[y] = [...this.playfield[y]];
    }
```
4. Some nested loops and enclosed or complex multiline if-statements is a subject to optimize and refactor

**Comment by tshemsedinov** [comment]
You have 99

**Comment by TsNikolay** [comment]
Thank you for the code review. I have fixed these bugs and if it possible, can I get 100 points now?

**Comment by TsNikolay** [comment]
Добрый день, спасибо за ваше письмо.
Я ознакомился с недочётами, повторно отрефакторил код и исправил
вышеперечисленные ошибки.
И сейчас если это возможно, могу ли я получить 100 баллов?
С уважением, Царик Николай

пт, 13 янв. 2023 г. в 22:17, Timur Shemsedinov ***@***.***>:
